<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="moao"
    nsURI="http://com.rcpcompany/schemas/moao.ecore" nsPrefix="moao">
  <eClassifiers xsi:type="ecore:EClass" name="MOAO" eSuperTypes="#//IAdaptable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="facets" upperBound="-1"
        eType="#//MOAOFacet" containment="true" resolveProxies="false" eOpposite="#//MOAOFacet/object"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MOAOFacet" abstract="true" eSuperTypes="#//MOAO">
    <eStructuralFeatures xsi:type="ecore:EReference" name="object" eType="#//MOAO"
        resolveProxies="false" eOpposite="#//MOAO/facets"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedObject" eSuperTypes="#//MOAO">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uuid" lowerBound="1" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"
        derived="true" iD="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="suppressedSetVisibility" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IAdaptable" instanceClassName="org.eclipse.core.runtime.IAdaptable"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EDataType" name="DiagnosticChain" instanceClassName="org.eclipse.emf.common.util.DiagnosticChain"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Map" instanceClassName="java.util.Map">
    <eTypeParameters name="K"/>
    <eTypeParameters name="V"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MOAOMessage" eSuperTypes="#//MOAOFacet">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="owner" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="feature" eType="#//EStructuralFeature"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="severity" eType="#//Severity"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="details" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Severity">
    <eLiterals name="WARNING" literal="Warning"/>
    <eLiterals name="ERROR" value="1" literal="Error"/>
    <eLiterals name="INFO" value="2" literal="Info"/>
    <eLiterals name="COMMENT" value="3" literal="Comment"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EStructuralFeature" instanceClassName="org.eclipse.emf.ecore.EStructuralFeature"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Exception" instanceClassName="java.lang.Exception"
      serializable="false"/>
</ecore:EPackage>
