<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="navigator" nsURI="http://rcp-company.com/schemas/uibindings/navigator"
    nsPrefix="navigator">
  <eClassifiers xsi:type="ecore:EClass" name="NavigatorManager">
    <eStructuralFeatures xsi:type="ecore:EReference" name="navigators" upperBound="-1"
        eType="#//NavigatorDescriptor" transient="true" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="descriptors" upperBound="-1"
        eType="#//EditorPartDescriptor" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="editorInformations" upperBound="-1"
        eType="#//EditorInformation" transient="true" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="useGenericEditorPartFallback"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pinEditorByDefault" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="openMustOpenNew" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="preferenceModelTypes" upperBound="-1"
        transient="true">
      <eGenericType eClassifier="ecore:EDataType ../../com.rcpcompany.uibindings/model/uibindings.ecore#//CEObjectHolder">
        <eTypeArguments eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      </eGenericType>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NavigatorDescriptor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="advisor" lowerBound="1"
        transient="true">
      <eGenericType eClassifier="ecore:EDataType ../../com.rcpcompany.uibindings/model/uibindings.ecore#//CEObjectHolder">
        <eTypeArguments eClassifier="#//INavigatorBaseViewAdvisor"/>
      </eGenericType>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EditorInformation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="editors" upperBound="-1"
        eType="#//EditorPartDescriptor" transient="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="preferredEditor" eType="#//EditorPartDescriptor"
        transient="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="modelType" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="treeItemID" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EditorPartDescriptor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="modelTypes" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="treeItemIDs" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="priority" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fallbackEditor" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="factory" lowerBound="1"
        transient="true">
      <eGenericType eClassifier="ecore:EDataType ../../com.rcpcompany.uibindings/model/uibindings.ecore#//CEObjectHolder">
        <eTypeArguments eClassifier="#//IEditorPartFactory"/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="image" lowerBound="1" eType="ecore:EDataType ../../com.rcpcompany.uibindings/model/uibindings.ecore#//CEResourceHolder"
        transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="enabledWhenExpression"
        eType="#//Expression" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IEditorPartFactory" instanceClassName="com.rcpcompany.uibindings.navigator.IEditorPartFactory"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="INavigatorBaseViewAdvisor" instanceClassName="com.rcpcompany.uibindings.navigator.views.INavigatorBaseViewAdvisor"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="IEditorPartView" instanceClassName="com.rcpcompany.uibindings.navigator.IEditorPartView"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="StringToEditorInformationMapEntry" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//EditorInformation"
        transient="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Expression" instanceClassName="org.eclipse.core.expressions.Expression"
      serializable="false"/>
</ecore:EPackage>
