<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="shop"
    nsURI="http://rcp-company.com/schemas/shop.ecore" nsPrefix="shop">
  <eClassifiers xsi:type="ecore:EClass" name="Shop" eSuperTypes="../../com.rcpcompany.uibindings.moao/model/moao.ecore#//NamedObject">
    <eOperations name="save"/>
    <eOperations name="nameLengthOK" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="diagnostics" lowerBound="1" eType="#//DiagnosticChain"/>
      <eParameters name="context">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nextOrderNo" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nextCustomerNo" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tmpDir" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral="C:\Windows\Temp"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="countries" upperBound="-1"
        eType="#//Country" containment="true" resolveProxies="false" eOpposite="#//Country/shop"
        eKeys="#//Country/abbreviation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contacts" upperBound="-1"
        eType="#//Contact" containment="true" resolveProxies="false" eOpposite="#//Contact/shop"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="shopItems" upperBound="-1"
        eType="#//ShopItem" containment="true" resolveProxies="false" eOpposite="#//ShopItem/shop"
        eKeys="../../com.rcpcompany.uibindings.moao/model/moao.ecore#//NamedObject/name"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="orders" upperBound="-1"
        eType="#//Order" containment="true" resolveProxies="false" eOpposite="#//Order/shop"
        eKeys="#//Order/no"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="customers" upperBound="-1"
        eType="#//Customer" containment="true" resolveProxies="false" eOpposite="#//Customer/shop"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="shopGroups" upperBound="-1"
        eType="#//ShopItemGroup" containment="true" resolveProxies="false" eOpposite="#//ShopItemGroup/shop"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="infos" upperBound="-1"
        eType="#//ShopInformation" transient="true" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Customer" eSuperTypes="../../com.rcpcompany.uibindings.moao/model/moao.ecore#//MOAO">
    <eStructuralFeatures xsi:type="ecore:EReference" name="shop" lowerBound="1" eType="#//Shop"
        resolveProxies="false" eOpposite="#//Shop/customers"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contact" lowerBound="1"
        eType="#//Contact" resolveProxies="false" eOpposite="#//Contact/customer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="orders" upperBound="-1"
        eType="#//Order" resolveProxies="false" eOpposite="#//Order/customer"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="loyalty" eType="#//CustomerType"
        defaultValueLiteral="BRONCE"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="logoFileName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ShopItem" eSuperTypes="../../com.rcpcompany.uibindings.moao/model/moao.ecore#//NamedObject">
    <eOperations name="namePriceOK" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="diagnostics" lowerBound="1" eType="#//DiagnosticChain"/>
      <eParameters name="context">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="nameOK" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="diagnostics" lowerBound="1" eType="#//DiagnosticChain"/>
      <eParameters name="context">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="shop" lowerBound="1" eType="#//Shop"
        resolveProxies="false" eOpposite="#//Shop/shopItems"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="price" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="orderItems" upperBound="-1"
        eType="#//OrderItem" transient="true" resolveProxies="false" eOpposite="#//OrderItem/item"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="forSale" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="information" eType="#//ShopItemInformation"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="group" eType="#//ShopItemGroup"
        eOpposite="#//ShopItemGroup/items"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="locations" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//ShopItemProperties" resolveProxies="false" eOpposite="#//ShopItemProperties/item"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ShopItemProperties" eSuperTypes="../../com.rcpcompany.uibindings.moao/model/moao.ecore#//NamedObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="item" eType="#//ShopItem"
        eOpposite="#//ShopItem/properties" eKeys="../../com.rcpcompany.uibindings.moao/model/moao.ecore#//NamedObject/name"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ShopItemGroup" eSuperTypes="../../com.rcpcompany.uibindings.moao/model/moao.ecore#//NamedObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="items" upperBound="-1"
        eType="#//ShopItem" eOpposite="#//ShopItem/group"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="shop" lowerBound="1" eType="#//Shop"
        resolveProxies="false" eOpposite="#//Shop/shopGroups"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Order" eSuperTypes="../../com.rcpcompany.uibindings.moao/model/moao.ecore#//MOAO">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="no" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="shop" lowerBound="1" eType="#//Shop"
        changeable="false" derived="true" resolveProxies="false" eOpposite="#//Shop/orders"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="customer" eType="#//Customer"
        resolveProxies="false" eOpposite="#//Customer/orders"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="price" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="items" upperBound="2" eType="#//OrderItem"
        containment="true" resolveProxies="false" eOpposite="#//OrderItem/order" eKeys="#//OrderItem/no"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OrderItem" eSuperTypes="../../com.rcpcompany.uibindings.moao/model/moao.ecore#//MOAO">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="no" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="order" lowerBound="1" eType="#//Order"
        resolveProxies="false" eOpposite="#//Order/items"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="item" lowerBound="1" eType="#//ShopItem"
        resolveProxies="false" eOpposite="#//ShopItem/orderItems"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="count" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Contact" eSuperTypes="../../com.rcpcompany.uibindings.moao/model/moao.ecore#//NamedObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="shop" lowerBound="1" eType="#//Shop"
        resolveProxies="false" eOpposite="#//Shop/contacts"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="address" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="city" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="zip" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="country" lowerBound="1"
        eType="#//Country" resolveProxies="false" eOpposite="#//Country/contacts"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="customer" eType="#//Customer"
        resolveProxies="false" eOpposite="#//Customer/contact"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="newsletter" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="birthday" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Country" eSuperTypes="../../com.rcpcompany.uibindings.moao/model/moao.ecore#//NamedObject">
    <eAnnotations source="http://rcp-company.com/schemas/uibindings">
      <details key="featureName" value="abbreviation"/>
    </eAnnotations>
    <eOperations name="abbreviationLengthOK" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="diagnostics" lowerBound="1" eType="#//DiagnosticChain"/>
      <eParameters name="context">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="abbreviationCaseOK" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="diagnostics" lowerBound="1" eType="#//DiagnosticChain"/>
      <eParameters name="context">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="shop" lowerBound="1" eType="#//Shop"
        resolveProxies="false" eOpposite="#//Shop/countries"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="abbreviation" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contacts" upperBound="-1"
        eType="#//Contact" eOpposite="#//Contact/country"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CustomerType">
    <eLiterals name="BRONCE" literal="Bronce"/>
    <eLiterals name="SILVER" value="1" literal="Silver"/>
    <eLiterals name="GOLD" value="2" literal="Gold"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="DiagnosticChain" instanceClassName="org.eclipse.emf.common.util.DiagnosticChain"/>
  <eClassifiers xsi:type="ecore:EClass" name="ShopItemInformation" eSuperTypes="../../com.rcpcompany.uibindings.moao/model/moao.ecore#//MOAO"/>
  <eClassifiers xsi:type="ecore:EClass" name="ShopItemDescription" eSuperTypes="#//ShopItemInformation"/>
  <eClassifiers xsi:type="ecore:EClass" name="ShopItemURL" eSuperTypes="#//ShopItemInformation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="url" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ShopInformation" abstract="true" eSuperTypes="../../com.rcpcompany.uibindings.moao/model/moao.ecore#//NamedObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="ShopURL" eSuperTypes="#//ShopInformation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="url" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ShopAddress" eSuperTypes="#//ShopInformation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="url" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
